# App config
server:
  port: 8090

spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@blog-project.afmphqb.mongodb.net/?retryWrites=true&w=majority
      database: blog-project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost